name: Front Deployment
on:
    push:
      branches: [master]
jobs:
  deployment:
    name: deployment front
    runs-on: ubuntu-latest
    steps:
      - name: deploy front server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/git/front-front-office/
            git pull origin master
            git status
